config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Update your flat</h1>
<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/index.html.erb
<div class="container">
<div class="row">


<ul class="col-12 col-lg-6">
  <% @flats.each do |flat| %>
    <li><%= link_to flat.name, flat_path(flat)%></li>
    <%= flat.address%> <br>
    <%= flat.description%> <br>
    <hr>
  <% end %>
</ul>
</div>
</div>

<a href="flats/new">Add a new flat</a>




      <h2>Mobile full-screen, laptop half-half</h2>

      <div class="row">

        <div class="col-12 col-lg-6">
        <div class="card bg-light">
          😀
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="card bg-light">
          😀
        </div>
      </div>

      </div>

    </div>

app/views/flats/new.html.erb
<h1>New flat</h1>
<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<h2><%= @flat.name %></h2>
<p> <strong>Address :</strong> <%= @flat.address %></p>
<p> <strong>Description :</strong> <%= @flat.description %></p>
<p> <strong>Price per night :</strong> <%= @flat.price_per_night %></p>
<p> <strong>Number of guests :</strong> <%= @flat.number_of_guests %></p>



<%= link_to "Delete",
  flat_path(@flat),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<a href="/flats">Back to list</a>
 <%= link_to "Edit", edit_flat_path(@flat)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>